services:
  - type: web
    name: benjamin-be
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: CORS_ORIGIN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: COACH_PASSCODE
        sync: false
      - key: NODE_VERSION
        value: "20"
